### ISSUE TITLE
Unable to start Windows service (after Creator update?)

### ISSUE THREAD

**Issue by Frank071** [SickRage/SickRage#3629]
In its current form the SickRage service won't start automatically, something I noticed after performing the Creators Update. This is due to an issue with NSSM. On the site (nssm.cc) is stated that services that try to create a console window (now) fail. The workaround is to edit the service and set it to not open a console window (tab 'Process').
I am putting it here as probably more people will stumble upon this issue and it avoids a lot of searching if you know this is the solution. And it might be worthwhile to change the installation script so it does no longer have the checkbox checked after a fresh install.

**Comment by sharkykh** [comment]
This issue was already discussed in #3070 
> And it might be worthwhile to change the installation script so it does no longer have the checkbox checked after a fresh install.

It's already been done - see v0.5.1 @ [SickRage/SickRageInstaller](https://github.com/SickRage/SickRageInstaller/releases).
However because the old installer was built by VinceVal,
you don't get the update about a new installer being available,
so users have to know about the newer version in order download it.
