### ISSUE TITLE
Shows list doesn't load with browser Brave shield feature UP

### ISSUE THREAD

**Issue by kriegalex** [SickRage/SickRage#3639]
It would be interesting to know what in Sickrage makes it being blocked by Brave's shield

Branch/Commit: master
OS: Windows 10 x64
What you did: Open the URL of Sickrage
What happened: List of shows doesn't appear
What you expected: List of shows to appear
Logs:
No logs produced

**Comment by OmgImAlexis** [comment]
What are you settings for Brave in the shield section? I'm not having any issue with a fresh install of Brave.

**Comment by kriegalex** [comment]
I didn't touch it, it's the default : 

Ad Control : block ads
Cookie Control : block 3rd party cookies
HTTPS everywhere on
Block Phising Malware

I tried some stuff and it's the Cookie Control that must be set to allow cookies for Sickrage

**Comment by OmgImAlexis** [comment]
Well without cookies 99% of sites are going to stop working so it seems more like a browser issue than anything with Sickrage.

**Comment by kriegalex** [comment]
I understand what you say, but most websites keep working with the blocking of cookies active. If I remember correctly my old web dev knowledge, cookies are used to remember information about the user, so it shouldn't prevent the show list to load ?

**Comment by OmgImAlexis** [comment]
Since I can't reproduce this at all I'm not sure what to say. If you have cookies set to disabled then there's all sorts of issues that could happen because of the way Sickrage loads in assets. 

![screen shot 2017-04-23 at 1 00 56 pm](https://cloud.githubusercontent.com/assets/6525926/25310511/04223f1e-2825-11e7-823a-851e64fa5d89.png)
![screen shot 2017-04-23 at 1 00 50 pm](https://cloud.githubusercontent.com/assets/6525926/25310510/0421ef00-2825-11e7-930c-6c3e4f3ebbb4.png)
