### ISSUE TITLE
Sickrage showing (and using?) wrong SSL version?

### ISSUE THREAD

**Issue by jeanpaulrh** [SickRage/SickRage#3678]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Openmediavault / Linux Debian
What you did: I tried to figure out why pushbullet notification weren't working anymore
What happened: I saw in the logs some complaint about wrong SSL version
What you expected: I followed the instruction about pip downgrading pyOpenSSL to version 0.13, since I have python 2.7.3, I checked my ssl version which is 1.0t, but if I check the help & info page on sickrage it shows openssl version 0.9.8 (which is installed into my system, but it shouldn't be used AFAIK).
Logs:
```
sickbeard@openmediavault:~$ python -c "import ssl; print ssl.OPENSSL_VERSION"
OpenSSL 1.0.1t  3 May 2016

sickbeard@openmediavault:~$ python --version
Python 2.7.3

sickbeard@openmediavault:~$ openssl version
OpenSSL 1.0.1t  3 May 2016

sickbeard@openmediavault:~$ pip show pyOpenSSL
Name: pyOpenSSL
Version: 0.13.1
Summary: Python wrapper module around the OpenSSL library
Home-page: http://pyopenssl.sourceforge.net/
Author: Jean-Paul Calderone
Author-email: exarkun@twistedmatrix.com
License: APL2
Location: /usr/local/lib/python2.7/dist-packages

2017-04-27 08:35:09 INFO     Thread-14 :: SSL Error requesting url: 'https://api.pushbullet.com/v2/devices' You have OpenSSL 0.9.8o 01 Jun 2010, try upgrading OpenSSL to 1.0.1e+
2017-04-27 08:35:09 INFO     Thread-14 :: SSL Error requesting url: '{0}' Try disabling Cert Verification on the advanced tab of /config/general

```
I even tried disabling ssl cert verification in Config Advanced but the message remains..

**Comment by sharkykh** [comment]
@jeanpaulrh I think the `requests` module uses pyOpenSSL internally in some cases. Not sure which.
May I ask why Python 2.7.3? It's quite old. I think SR works best on 2.7.9 or newer.

**Comment by sharkykh** [comment]
Also, please enable debug logging and post the debug logs after trying again. Current logs don't contain enough information.

**Comment by jeanpaulrh** [comment]
I'll try that.
I know python is quite old, but my distro has that version...
I'll try to update it if I can and to enable debug log.
Thanks.

**Comment by Nicode70** [comment]
Hi, i have the very same issue:

openssl version
OpenSSL 1.0.2j  26 Sep 2016

python --version
Python 2.7.13

pip show pyOpenSSL
Name: pyOpenSSL
Version: 16.2.0

In sickrage info page i see: 
  Python Version: 2.7.10 (default, Feb 6 2017, 23:53:20) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
  SSL Version: OpenSSL 0.9.8zh 14 Jan 2016

and the logs shows:
2017-04-28 15:47:23 INFO     SEARCHQUEUE-MANUAL-279536 :: [T411] :: SSL Error requesting url: 'https://api.t411.ai/auth' You have OpenSSL 0.9.8zh 14 Jan 2016, try upgrading OpenSSL to 1.0.1e+
2017-04-28 15:47:23 DEBUG    SEARCHQUEUE-MANUAL-279536 :: [T411] :: Request failed: EOF occurred in violation of protocol (_ssl.c:590)
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
2017-04-28 15:47:24 INFO     SEARCHQUEUE-MANUAL-279536 :: [XThor] :: SSL Error requesting url: 'https://api.xthor.bz/?search=Billions+S02E10&passkey=********************************' You have OpenSSL 0.9.8zh 14 Jan 2016, try upgrading OpenSSL to 1.0.1e+

Thank you for your help

**Comment by sharkykh** [comment]
@Nicode70 SickRage is running using **a different Python interpreter**. You should be running SickRage using the Python in the path you get by running `which python` (Unix) or `where python` (Windows)
That _might not_ fix the issue for you, but it's still a good practice.

**Comment by Nicode70** [comment]
Thank you for that @sharkykh .
which python
/Library/Frameworks/Python.framework/Versions/2.7/bin/python

How do i change the path sickrage runs in?

**Comment by sharkykh** [comment]
Well, that depends.. You're on OSX so I'm not sure.
How to you start SickRage?
You're using systemd?

**Comment by sharkykh** [comment]
@Nicode70 
Just found out. Assuming you followed https://www.htpcguides.com/install-sickrage-mac-osx-usenet-torrent-tv/
What does `cat /Library/LaunchDaemons/sickrage.plist` print for you?

**Comment by Nicode70** [comment]
Yes, that's how i installed sickrage!

here what i get:
$ /Library/Frameworks/Python.framework/Versions/2.7/bin/python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 12:39:47) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by sharkykh** [comment]
@Nicode70 You ran the wrong command ;)

**Comment by Nicode70** [comment]
sorry 
$ cat /Library/LaunchDaemons/sickrage.plist
cat: /Library/LaunchDaemons/sickrage.plist: No such file or directory

**Comment by sharkykh** [comment]
Maybe you need `sudo` for that?
```
sudo cat /Library/LaunchDaemons/sickrage.plist
```

**Comment by Nicode70** [comment]
nope. same problem, no such file or directory

**Comment by Nicode70** [comment]
i don't use the plist method to launch sichrage. 
i use the applescript method

**Comment by sharkykh** [comment]
Then you probably used this "Automator" method.
Open Automator and you need to somehow find the SickRage application,
then edit it and post the applescript here

**Comment by Nicode70** [comment]
here is the script: 
do shell script "python /Applications/SickRage/SickBeard.py" password "password" with administrator privileges

**Comment by sharkykh** [comment]
OK, so to be on the safe side change it to:
```applescript
do shell script "/Library/Frameworks/Python.framework/Versions/2.7/bin/python /Applications/SickRage/SickBeard.py" password "password" with administrator privileges
```

**Comment by Nicode70** [comment]
17:43:46 DEBUG::MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
17:43:46 DEBUG::MAIN :: Found codec for 'Show Name: Ep Name'.
17:43:46 DEBUG::MAIN :: Episode has no release group, replacing it with 'RLSGROUP'
17:43:46 DEBUG::MAIN :: formatting pattern: %SN - S%0SE%0E - %EN -> Show Name - S02E03 - Ep Name
17:43:46 DEBUG::MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
17:43:46 DEBUG::MAIN :: Found codec for 'Show Name: Ep Name'.
17:43:46 DEBUG::MAIN :: formatting pattern: Season %0S -> Season 02
17:43:46 DEBUG::MAIN :: Trying to parse Show Name - S02E03 - Ep Name.ext
17:43:46 DEBUG::MAIN :: Parsed Show Name - S02E03 - Ep Name.ext into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
17:43:46 DEBUG::MAIN :: The name Show Name - S02E03 - Ep Name.ext parsed into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
17:43:46 DEBUG::MAIN :: Checking database structure...sickbeard.db
17:43:46 DEBUG::MAIN :: Database upgrade required: Reset Version
17:43:46 DEBUG::MAIN :: ResetDBVersion upgrade completed
17:43:46 DEBUG::MAIN :: Checking database structure...cache.db
17:43:46 DEBUG::MAIN :: Checking database structure...failed.db
17:43:46 DEBUG::MAIN :: Checking for shows with tvrage id's, since tvrage is gone
17:43:46 DEBUG::MAIN :: Checking for archived episodes not qualified
17:43:46 DEBUG::MAIN :: Checking if we can use git commands: git version
17:43:46 DEBUG::MAIN :: Executing git version with your shell in /Applications/SickRage
17:43:47 DEBUG::MAIN :: git version : returned successful
17:43:47 DEBUG::MAIN :: Using: git
17:43:47 DEBUG::MAIN :: Executing git symbolic-ref -q HEAD with your shell in /Applications/SickRage
17:43:47 DEBUG::MAIN :: git symbolic-ref -q HEAD : returned successful
17:43:47 DEBUG::MAIN :: Retrieving the last check time from the DB
17:43:47 DEBUG::MAIN :: Loading initial show list
17:43:47 INFO::MAIN :: Starting SickRage [master] using '/Applications/SickRage/config.ini'
17:43:47 INFO::TORNADO :: Starting SickRage on https://0.0.0.0:8081/
17:43:47 INFO::TORNADO :: Could not start webserver on port 8081: already in use!

**Comment by sharkykh** [comment]
Then restart your computer...

**Comment by Nicode70** [comment]
thank you very much @sharkykh !

now the python version on the info page has updated. But sadly not the openssl version.

BUT: i don't have the need to open the openssl message in the logs anymore

**Comment by sharkykh** [comment]
@Nicode70 
After a restart the error messages are reset. Try searching for an episode using T411 again.

**Comment by Nicode70** [comment]
IT's working! search returned results. Thank you very much for your help and sorry for my low understanding of those things. 

sickrage is really great, almost magic for me.

**Comment by jeanpaulrh** [comment]
Upgraded python to 2.7.13. 
So far so good.

Thanks
