### ISSUE TITLE
Unable to use UNC paths for show folder locations after recent update

### ISSUE THREAD

**Issue by josurr** [SickRage/SickRage#3729]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** master/b5b2262ad0acfd0ca679b1964950a147dfc5e193

**Version:** v2017.05.07-1

**OS:** Windows 7 x64 SP1

**What you did:** Manual/Automatic postprocessing

**What happened:** SR/nzbToMedia complains about no free space in destination (Destination location has 4+ TB free). SR also states that the Media Root Directory (`\\[internal IP]\[share name]\Shows`) is missing. I can manually browse to that location and the SR service is running as the current logged in user in Windows.

**What you expected:** shows process normally (renamed and moved to final location) and the shows page in SR no longer state that the location folder is missing.

**Comment by sharkykh** [comment]
I don't think anything was changed in this section of SickRage.

Sometimes when you restart Windows, it takes some time for it to discover network locations and shares.

* Have you tried restarting SickRage?
* Have you tried using mapped network drives instead?

**Comment by josurr** [comment]
When I try to specify the UNC path in the "Root" text field, it attempts to connect to the location (the spinning icon in the bottom left of the pop-in frame shows up) but then refreshes the list of the local drives.

Mapped drives do not show up in the selector option for Root directory anymore either.

I have restarted SR, but not Windows yet.

**Comment by sharkykh** [comment]
@josurr

I believe the file browser can be a bit misleading.
1. Whatever you enter in the "Root" field is accepted, no matter what, when you press **Ok** at the bottom of the browser. Try that out.

2. If I enter just the local IP address of my share it behaves the same way you're describing.
However, when I type a valid share name after it, the contents shows up for me:
![image](https://cloud.githubusercontent.com/assets/10238474/25817395/e60f97bc-342f-11e7-92cd-86fbfe90518e.png)

3. Indeed, mapped drives do not show for me in the browser too.
However they should still be accessible if you enter them manually, like explained in (1).

> I have restarted SR, but not Windows yet.

I actually meant SR alone.
Because if you using SR as a service it probably loads before Windows can connect to the network locations, causing issues. I load SR with a delay (edited the service in `services.msc`)
![image](https://cloud.githubusercontent.com/assets/10238474/25817643/a28415da-3430-11e7-9d5b-7c251a9febba.png)

**Comment by josurr** [comment]
My SR install is not behaving like that any more. It does take whatever is entered into the Root field, but it still does not find anything in the UNC location specified.
![sr_directory_missing](https://cloud.githubusercontent.com/assets/14187881/25818159/86ee4842-33de-11e7-9740-879f97efd37a.png)

![sr_not_showing_contents_of_unc_location](https://cloud.githubusercontent.com/assets/14187881/25818158/86edbf62-33de-11e7-98b0-52711da976a5.png)

![unc_path_exists](https://cloud.githubusercontent.com/assets/14187881/25818160/86ee6516-33de-11e7-8d4b-e04940cf5fc4.png)

**Comment by sharkykh** [comment]
If you go to http://ip:8081/config, under user your username shows up?

Is this intended that you have Shows twice in the path?

**Comment by josurr** [comment]
yes (re: shows twice in the UNC path)

and it does show the username of the logged in Windows account that has access to that UNC location

![image](https://cloud.githubusercontent.com/assets/14187881/25819520/110dcc7e-33e3-11e7-9604-48775f9e3157.png)

**Comment by josurr** [comment]
Issue was found to be the server hosting the UNC location. It was active for established connections, but any new connection attempts were met with "network path not found". Rebooting that server fixed the issue in SR.

thanks for the assistance @sharkykh!
