### ISSUE TITLE
rarbg no longer working

### ISSUE THREAD

**Issue by glc650** [SickRage/SickRage#3733]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:  master/b5b2262ad0acfd0ca679b1964950a147dfc5e193
OS:  Windows 10 Pro x64
What you did: manual/auto search
What happened:  cannot download from rarbg any more
What you expected: downloading from this provider was working fine up until a few days ago
Logs:
```
18:52:34 INFO::SEARCHQUEUE-MANUAL-274431 :: [Rarbg] :: Request failed: 403 Client Error: Forbidden for url: http://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=sickrage2&format=json
18:52:34 WARNING::SEARCHQUEUE-MANUAL-274431 :: [Rarbg] :: Unable to connect to provider
```

**Comment by sharkykh** [comment]
@glc650 
Works fine for me, just downloaded an hour ago.
Are you using Avast Anti-Virus?

**Comment by glc650** [comment]
No anti-virus.  My configured providers are rarbg and piratebay and rarbg is the only one I'm having issues with at the moment.

All I see is a blank white page with {"token":"yo0nwhif3l"} when going to that url.  That's from Firefox on the PC running SickRage

**Comment by sharkykh** [comment]
@glc650 Are you using VPN/Proxy on the machine? There was a similar issue some time ago: #2164

**Comment by BenBeyond** [comment]
Just wanted to drop in and say that I am also having this issue. No VPN or proxy on my machine.  Sickrage details are as follows:

Branch: master
Commit: b5b2262ad0acfd0ca679b1964950a147dfc5e193
Database Version: 44.0
Python Version: 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
OS: Linux-4.4.0-53-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by glc650** [comment]
After restarting everything it seems to be working now.

**Comment by TTLucian** [comment]
2017-12-15 09:33:24 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Request failed: HTTPConnectionPool(host='torrentapi.org', port=80): Max retries exceeded with url: /pubapi_v2.php?get_token=get_token&app_id=sickrage2&format=json (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000000FDE1A58>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
2017-12-15 09:33:24 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Unable to connect to provider
