### ISSUE TITLE
Can't start sickrage after qnap 4.3.3.0188

### ISSUE THREAD

**Issue by matthewjoliver** [SickRage/SickRage#3814]
```
# /etc/init.d/sickbeard-tvrage.sh start             
x86_64
git is disabled.
```

**Comment by oodonnell** [comment]
update GIT to the 64 bit version

you will most likely still get an error in sickrage about git  however its easy fixed by going in to general settings -> Advanced settings and setting the Git executable path to:
/opt/bin/git

if that doesn't set it you may need to ssh/putty in and then type git init so that QTS recognises it.

I will point out that i dont quite know what a lot of this does, but for hte last 30 minutes ive had to trawl through google to get it resolved

**Comment by sharkykh** [comment]
@matthewjoliver Seems like you got an answer elsewhere
https://www.bountysource.com/issues/45701963-can-t-start-sickrage-after-qnap-4-3-3-0188
Did that work?

**Comment by oodonnell** [comment]
I didn't think it was the correct answer so i deleted it

Git was giving me several errors, its easy to fix using SSH/Putty and just running opkg upgrade git and then using a few git commands to get QTS 4.3.3 to recognise git is back. 


use ssh and do:

opkg install git or opkg upgrade git

then use ;

opkg install git-http 

upgrading to 4.3.3 has been great but so many programs stopped working since, having to reinstall most or use the upgrade commands using entware/opkg 

I had to finally use git init but that was my own issue and not relevant to this, it was to do with getting the NAS to recognise git was available as it was giving error messages

**Comment by matthewjoliver** [comment]
Yes, it worked re-installing git and git-http.
Thanks guys!

**Comment by royteeuwen** [comment]
Hey @matthewjoliver @oodonnell ,

Could anyone of you pass me a guide on how to set up sickrage or give me the startup script? I have installed Entware opkg, git and git-http, but I still need to have a init.d startup script to actually start it up, and maybe another python version than the one standard included (pre installed is 2.7.5) ?

Thanks!
Roy

**Comment by matthewjoliver** [comment]
Hey @royteeuwen,

You can install both Sickrage and latest Python with Entware. Here's a guide to install on QNap: [https://forum.qnap.com/viewtopic.php?f=223&t=118366](url)

**Comment by royteeuwen** [comment]
Hey @matthewjoliver ,

Thanks! Sadly enough it doesn't seem to work :(. It says "SickBeard-TVRage 151227 installation failed. The following QPKG must be installed and enabled: git, python."

Anyone any idea? Is it possible to just start from git / source? Cant seem to find a qpkg that works (tried like 3 different ones)

Thanks,
Roy

**Comment by matthewjoliver** [comment]
Have you followed these instructions?:
[https://github.com/Entware-ng/Entware-ng/wiki/Install-on-QNAP-NAS](url)
[https://github.com/SickRage/SickRage/wiki/Sickrage-installation-packages](url)
