### ISSUE TITLE
Missing Season and Wrong Episodes.

### ISSUE THREAD

**Issue by Myran67** [SickRage/SickRage#3833]
Hi 
I Added Top Gear US and notised that Season 05 is missing and also that Season 05s EPs are submitted in Season 04. 
Is there any way to fix this ? 

Thanks :) 
![topgearus](https://cloud.githubusercontent.com/assets/29196035/26778765/f691aeea-49e2-11e7-82df-bc71fc977be3.jpg)

### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Windows 10
What you did: Added a new Serie TopGear US
What happened: Missing Season 5
What you expected: 
Logs:
```
PASTE LOGS HERE
```

**Comment by sharkykh** [comment]
Take a look at the entry on TheTVDB.com: http://thetvdb.com/?tab=series&id=199051&lid=7
As you can see, season 5 is non-existent.
As a rule of thumb, know that whenever you have items with no episode name on the episode list,
that means there's a mismatch between the episode numbering you use, to what TVDB uses (anime shows excluded, since sometimes XEM is involved).

I don't know if the change on TheTVDB was intended (you should check their forums),
but if you want SickRage to list the episode properly, change the filenames of those episodes to match the episode list.
You can see the filenames by clicking the `Select Columns` drop-down menu and selecting `Filename`.

**Comment by Myran67** [comment]
Hi And thanks for your answer. 
Well There is a missmatch according to every other sites on TheTVDB but its locked and it sees like no one can change th Season 4 and add Season 5 of Top Gear US 
https://forums.thetvdb.com/viewtopic.php?f=18&t=35829&p=111388&hilit=Top+Gear+US#p111388

So I have to hope that this "furby" that have locked it eventuly corrects it.

**Comment by sharkykh** [comment]
In any case, this isn't a SickRage issue, as we don't control our indexers.
