### ISSUE TITLE
One show cannot be found

### ISSUE THREAD

**Issue by demon8991** [SickRage/SickRage#3928]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Master/96b53dee713dc35ebf295d0f37a67b2a36fb4ea3
DSM 6.1.3-15152
Will not find Life's Too Short when adding shows

![image](https://user-images.githubusercontent.com/19523102/28243274-49a9acf6-6a07-11e7-9fe1-980dbf39bba3.png)

It is the only show that cannot be found, I have tried with or without the apostrophe added and remove the year of production. Check IMDB and thetvdb and both have the show listed there exactly as I have.

**Comment by sharkykh** [comment]
The reason is probably because you already have this show in your database.
You can make sure by looking at your logs. See https://github.com/SickRage/SickRage/issues/3631
Try navigating to Mass Update and look for it there, or just open http://localhost:8081/home/displayShow?show=249698

This is fixed in the next version (isn't released yet) - https://github.com/SickRage/SickRage/pull/3882

**Comment by demon8991** [comment]
Thanks for your help.

I removed and re added and it fixed the issue.
