### ISSUE TITLE
[Question] Backup API Call from bash

### ISSUE THREAD

**Issue by snow3461** [SickRage/SickRage#4029]
Hi,

I would like to know if there is an API call to run the backup function. I would like to schedule backups using cron and a bash script. 
What would be the best way to do it?

**Comment by OldskoolOrion** [comment]
Pack & move.. the SickRage backup only saves your fanart, databases, plus your configuration. This is ok to reinstall using a fresh install or grabbing the git-master usually (for the actual codebase).
However since I had a few times I was a bit too enthusiastic upgrading to latest version, to find out it actually broke my install, I started backing up my last working state by just keeping archived versions of a few key-directories. That way unpacking over the installation will always get me back to a working state with a maximum of losing just one day of updates, which quickly corrects itself once it's up again.
I upgrade manually these days, so there is no way the archived version could be a back up of a broken install and is always working - therefor only one copy of last 24hrs max needs to exist. You could of course script it to keep more copies (e.g. a week) which isn't hard : just needs an extra script deleting all archives older than a certain point in time.

Important directories to save in archived :
1) fanart / poster / banner / thumbnails
note : I delete all files in next two subdirectories (repopulate automatically) to minimize archivesize :
   SickRage/Data/cache/images/imdb_popular/*
   SickRage/Data/cache/images/trakt_trending/*
* archive to save fanart + poster + banner for your existing added tvshows :
   SickRage/Data/cache/images/*   (including all subdirectories, to also archive ./thumbnails/*)
2) databases + config
* archive to save all databases + your personal configuration :
   /SickRage/Data/*.db
   /SickRage/Data/*.ini
3) Codebase :
* archive to preserve current codebase + libraries + templates + etc :
  /SickRage/SickRage/*  (including all subdirectories)

Just unpacking this archive(s) to their original location gives you working state backup.

**Comment by snow3461** [comment]
Thank you for your input on this.

for the codebase, I consider using git as sufficient. If a new update doesnt work, I can always revert back to previous commits.

My concern is more about personnal files. 
No problem for images and thumbnail and so on. But for databases, I'm a bit concerned that a the time I perform a backup, Sickrage could be accessing/writing something in its databases, and maybe lead to a corrupt databases backup.

I had in mind that the backup button on the web Gui implemented a backup procedure that take necessary precautions. Like wait until current process is done before backing up. I could be wrong though.

I could of course stop sickrage before backing up, but thats not efficient.

So question are : 
* Is it dangerous to backup databases while sickrage is running (via a script) ?
* If yes, is there a way to make sickrage do the backup as if I pushed the backup button in webGUI?

**Comment by OldskoolOrion** [comment]
No it's not dangerous whatsoever.. SQLite is developed with just that in mind as one of the many advantages (there are disadvantages as well compared to database-installs but that's beyond the scope here) : being file-based cross-platform and rock-solid when it comes to copies / being backups. SQLite uses transactions that are atomic, consistent, isolated, and durable (ACID), even if the transaction is interrupted by a program crash, an operating system crash, or a power failure to the computer.

You could of course do it the "SQL-way" by coding it yourself and assigning a full dump instruction to a button or a menu-option somewhere in the code - as long as that's not in the main trunk and adopted by the maintainer, and thus not in the master repo, you would have to reapply those changes everytime there is an update. You could ask for it as a feature request, but I'm not sure if they would go for it, since the manual backup option is already there (altho they include the fanart).

Creating and scheduling a script is the best, most flexible way forward for you, since your aim is mainly preserving the database. You can easily schedule that multiple times a day, since the filesize of just those 4 files is next to nothing.  My personal database keeps track of 614 tv shows, spanning 12217 episodes and the database holding all that info is in total for the 4 files a mere 16MB in size.

**Comment by snow3461** [comment]
Ok, thats reassuring ! I was **too** worried.
I can do this without problem. 
Thanks again.
