### ISSUE TITLE
Is This Project Still Active ?

### ISSUE THREAD

**Issue by HPMSGEN8** [SickRage/SickRage#4095]
Hi Admins

There has been no news for months on what is going on and if there is even active members fixing bug issues etc...

If so can you please update the news feed.

Thanks

**Comment by OmgImAlexis** [comment]
Yes the last update to dev was less than a month ago. We all have day jobs, etc. so unless you're going to offer help please don't open issues like this.

**Comment by abetancort** [comment]
Appears that **SickRage** in last few months has evolved a  into a **_Walking Dead_** App...  IMHO, I believe that the best thing that could happen for the App and the community at this point is for the current **SickRage** development team to become aware that’s time to let go and for the current  repo-admin to take a step back into the background and silently pass the baton to a new team leader as soon as **there’s one willing to grab it**.  

Because sooner than later, and most surely before anyone would have expected the **App** will go from a **_Walking Dead_**  to an **Actual and Effective Dead App**. Obsolescence will turn it unusable I no time. And it will end up as what most people know as **abandonware**. 

I truly think, it would be pity after the huge amount of efforts put in time, sweat, all-nighters pulled coding and debugging and all the battles fought to get to this stage in the development of this App, known as “**_Official_**”  **SickRage fork**.
