### ISSUE TITLE
High memory Useage

### ISSUE THREAD

**Issue by clem16** [SickRage/SickRage#4208]
I seem to have high memory usage when sickrage is running. Anyone know what acceptable levels of usage is? Some benchmarks so I know if I’m within range.
Was wondering how sickrage handled it as well. It seems the more shows I add the more memory it’s using. I’ve not looked into the code for specifics but does anyone know if it’s slurping the whole database file into memory?

**Comment by BenjV** [comment]
Even the whole database is not a significant amount of memory.

But your question cannot be answered because it is a python application and python is working with a garbage collector to free up memory when not used anymore.
Also on all systems except windows, memory is kept in use and is only released when needed by another application.
It is almost impossible to measure the actual used memory of an application.

It is also useless.
Watch if you system is swapping, then you have not enough memory anymore.
