### ISSUE TITLE
Can't find show that is available on TheTVDB (Travelers 2016)

### ISSUE THREAD

**Issue by woutwoot** [SickRage/SickRage#4227]
Branch: master
Commit: 4b69468cc1ea330f598364718068352a54b0eb92
OS: Ubuntu server
What you did: Try adding show: Travelers (2016)
What happened: SickRage does not show the correct result, while it is available on TheTVDB
What you expected: The missing option for this show. Seems like this is a bug in the interaction with thetvdb.

Just to confirm, I did not have the show added to SickRage already, it is just not showing up in the results.

**Comment by miigotu** [comment]
Shows up just fine. Search it just like that in English `Travelers (2016)`

**Comment by unclenoriega** [comment]
I found this via Google while searching the same issue. It still seems like an issue even though it can be found with the search `Travelers (2016)`. Should it not show up while searching just `Travelers`? If `A.J.'s Time Travelers` and  `A Traveler's Guide to the Planets`, it seems a show with the exact title should also show up. In fact, when I try to add an existing Travelers (2016) show, it still doesn't show up, because SickRage searches "Travelers", even though the folder is "Travelers (2016).

**Comment by miigotu** [comment]
We dont control how tvdb returns results.
